# The purpose of this action is to run `document()` of the roxygen2 package on each commit.
# If new documentation was generated, it will automatically add a commit to the current branch.
# This has the same effect as running `document()` locally, but
#  * ensures it cannot be forgotten
#  * saves setting up the development environment locally, which is especially useful for new contributors.
#
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    paths: ["R/**", ".github/workflows"]

name: Document

jobs:
  document:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          needs: roxygen2

      - uses: pre-commit/action@v2.0.3

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: '!cancelled()'
        with:
          commit_message: Run pre-commit and roxygen